import './globals.css'
import { Roboto } from 'next/font/google'

const inter = Roboto({
  variable: '--font-roboto',
  weight: ['400', '700'],
  subsets: ['latin-ext']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-[#171133] text-white`}>
        {children}
      </body>
    </html>
  )
}
